abstract class ReadOnlyTextFormFieldsStates {}
class ReadOnlyTextFormFieldsInitialState extends ReadOnlyTextFormFieldsStates {}
class ReadOnlyTextFormFieldsChangedState extends ReadOnlyTextFormFieldsStates {}